apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  address: "redis-master:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  brokers: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092" 