apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-server.yaml
  - configmaps.yaml
  - secrets.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: polyid
  app.kubernetes.io/part-of: auth-platform

namespace: polyid-auth

configMapGenerator:
  - name: redis-config
    behavior: merge
    literals:
      - address=redis-master:6379
  - name: kafka-config
    behavior: merge
    literals:
      - brokers=kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092

secretGenerator:
  - name: db-credentials
    type: Opaque
    files:
      - username=./secrets/db-username
      - password=./secrets/db-password
      - endpoint=./secrets/db-endpoint 