apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # These are base64 encoded values. Replace with actual values in production
  username: BASE64_ENCODED_USERNAME
  password: BASE64_ENCODED_PASSWORD
  endpoint: BASE64_ENCODED_ENDPOINT 