# PolyID Configuration

server:
  port: 8080
  grpc_port: 9090
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

auth:
  jwt_secret: "${JWT_SECRET}"
  token_expiry: 3600s
  refresh_token_expiry: 604800s  # 7 days
  oidc:
    issuer: "https://auth.polyid.io"
    client_id: "${OIDC_CLIENT_ID}"
    client_secret: "${OIDC_CLIENT_SECRET}"

webauthn:
  rp_id: "auth.polyid.io"
  rp_origin: "https://auth.polyid.io"
  rp_name: "PolyID"
  attestation_preference: "direct"
  authenticator_attachment: "platform"
  resident_key: "preferred"
  user_verification: "preferred"

storage:
  nosql:
    endpoint: "${DB_ENDPOINT}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
    table_prefix: "polyid_"
    read_capacity: 100
    write_capacity: 100
  redis:
    address: "localhost:6379"
    password: "${REDIS_PASSWORD}"
    db: 0
    pool_size: 100

events:
  kafka:
    brokers:
      - "localhost:9092"
    topic_prefix: "polyid_"
    consumer_group: "polyid_auth"
  grpc:
    timeout: 5s
    max_retries: 3

security:
  kms:
    provider: "${KMS_PROVIDER}"
    key_id: "${KMS_KEY_ID}"
  threat_intel:
    enabled: true
    api_key: "${THREAT_INTEL_API_KEY}"
    update_interval: 300s
  privacy:
    fingerprint_budget: 100
    budget_reset_interval: 86400s  # 24 hours

monitoring:
  prometheus:
    enabled: true
    path: "/metrics"
  tracing:
    enabled: true
    jaeger_endpoint: "http://localhost:14268/api/traces" 